# Generated by Django 3.0.3 on 2020-04-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0002_profile_account_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signup_confirmation',
        ),
    ]
