# Generated by Django 3.0.3 on 2020-04-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0005_auto_20200428_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
