# Generated by Django 3.0.3 on 2020-04-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0006_profile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
    ]
