# Generated by Django 3.0.3 on 2020-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0014_auto_20200430_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
