# Generated by Django 3.0.3 on 2020-05-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0015_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='Profile_Image',
        ),
    ]
