# Generated by Django 3.0.3 on 2020-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0017_classlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='class_photo',
            field=models.ImageField(blank=True, upload_to='classphotos/'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='class_name',
            field=models.CharField(max_length=100),
        ),
    ]
