# Generated by Django 3.0.3 on 2020-05-04 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0018_auto_20200504_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateClassForm',
            fields=[
                ('classlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LMSSystem.ClassList')),
            ],
            bases=('LMSSystem.classlist',),
        ),
    ]
