# Generated by Django 3.0.3 on 2020-05-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0019_createclassform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateClassForm',
        ),
    ]
