# Generated by Django 3.0.3 on 2020-05-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0021_auto_20200504_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='class_description',
            field=models.TextField(default='N/a'),
        ),
    ]
