# Generated by Django 3.0.3 on 2020-05-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0022_classlist_class_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='class_subject',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='class_name',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='class_photo',
            field=models.ImageField(blank=True, null=True, upload_to='classphotos/'),
        ),
    ]
