# Generated by Django 3.0.3 on 2020-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0023_auto_20200511_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='syllabus_file',
            field=models.FileField(blank=True, upload_to='syllabus/'),
        ),
    ]
