# Generated by Django 3.0.3 on 2020-05-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0024_classlist_syllabus_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_description',
            field=models.TextField(default='Pending'),
        ),
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('assignment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(default='None', max_length=100)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.ClassList')),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(default='None', max_length=255)),
                ('assignment_description', models.TextField(default='Pending')),
                ('due_date', models.DateField()),
                ('point_value', models.IntegerField(default=0)),
                ('assignment_files', models.FileField(blank=True, upload_to='assignments/')),
                ('assignment_status', models.CharField(choices=[('Pending', 'Pending'), ('Published', 'Published'), ('Late', 'Late')], default='Pending', max_length=10)),
                ('assignment_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.AssignmentType')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.ClassList')),
            ],
        ),
    ]
