# Generated by Django 3.0.3 on 2020-05-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0025_auto_20200513_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='assignment_type_id',
        ),
        migrations.AddField(
            model_name='assignments',
            name='assignment_type',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
