# Generated by Django 3.0.3 on 2020-05-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0030_auto_20200514_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='class_id',
        ),
    ]
