# Generated by Django 3.0.3 on 2020-05-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0031_remove_assignments_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='class_id',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
