# Generated by Django 3.0.3 on 2020-05-14 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0032_assignments_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.ClassList'),
        ),
    ]
