# Generated by Django 3.0.3 on 2020-05-14 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LMSSystem', '0033_auto_20200514_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassListGroup',
            fields=[
                ('class_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_group_name', models.CharField(default='Class 1', max_length=100)),
                ('class_group_code', models.CharField(default='QPx6IBlMP4kdFGnKkh9DoVOAXOsnhKI0', max_length=32)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.ClassList')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
