# Generated by Django 3.0.3 on 2020-05-14 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0034_classlistgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroup',
            name='class_group_code',
            field=models.CharField(default='zmC5OqF9eBptulAv8rne7jqhDE3FSwcM', max_length=32),
        ),
        migrations.AlterField(
            model_name='classlistgroup',
            name='role',
            field=models.ForeignKey(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Supervisor', 'Supervisor')], on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.Profile'),
        ),
    ]
