# Generated by Django 3.0.3 on 2020-05-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0035_auto_20200514_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlistgroup',
            name='role',
        ),
        migrations.AlterField(
            model_name='classlistgroup',
            name='class_group_code',
            field=models.CharField(default='yPiwl2heYA2EcKcO0WQNHF3fdPmDs4Ql', max_length=32),
        ),
    ]
