# Generated by Django 3.0.3 on 2020-05-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0038_auto_20200514_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='VrlSsooiW9YB0fUjYahn1xpAfUzo9zU8', max_length=32),
        ),
    ]
