# Generated by Django 3.0.3 on 2020-05-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0039_auto_20200514_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='0us7BRCBvjecdQdJ6NagpaIiTGZ9KXX3', max_length=32),
        ),
    ]
