# Generated by Django 3.0.3 on 2020-05-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0042_auto_20200514_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='jHezw0eHwYy0Z7NLN1zqSb0HxeVZyinS', max_length=32),
        ),
    ]
