# Generated by Django 3.0.3 on 2020-05-15 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LMSSystem', '0043_auto_20200514_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroup',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classgroupassignment', to='LMSSystem.ClassList'),
        ),
        migrations.AlterField(
            model_name='classlistgroup',
            name='code_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classgroupassignment', to='LMSSystem.ClassListGroupCode'),
        ),
        migrations.AlterField(
            model_name='classlistgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classgroupassignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='nCVYZqEPFv0yBwR0onmmXAaxq5HVJO7n', max_length=32),
        ),
    ]
