# Generated by Django 3.0.3 on 2020-05-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0046_auto_20200515_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlistgroup',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classlistgroup',
            name='code_id',
        ),
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='6NVeK3jhY0Nqkho5f2mHtqXB5kkokI2b', max_length=32),
        ),
    ]
