# Generated by Django 3.0.3 on 2020-05-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0047_auto_20200515_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlistgroup',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='E58V8xv6OGZuTyT99cioAdGVuLOU8Lwx', max_length=32),
        ),
    ]
