# Generated by Django 3.0.3 on 2020-05-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0048_auto_20200515_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='TLKQYFGy0IYHPbuWyiqH5CQ8kmqUEejO', max_length=32),
        ),
        migrations.DeleteModel(
            name='ClassListGroup',
        ),
    ]
