# Generated by Django 3.0.3 on 2020-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0050_auto_20200515_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='ERs9EFMS7kpz4z2LkFbFQbAqDXtBBOqC', max_length=32),
        ),
    ]
