# Generated by Django 3.0.3 on 2020-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0051_auto_20200515_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='GyJe0qPO6HddgMMHlYR92OJenMpwqhjQ', max_length=32),
        ),
    ]
