# Generated by Django 3.0.3 on 2020-05-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0052_auto_20200515_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentWeight',
            fields=[
                ('assignment_weight_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_weight', models.IntegerField(default=0)),
                ('assignment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.Assignments')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.ClassList')),
            ],
        ),
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='5smCUFlvfxWrCZWJoCyaES48t3rxT9Et', max_length=32),
        ),
        migrations.DeleteModel(
            name='AssignmentType',
        ),
    ]
