# Generated by Django 3.0.3 on 2020-05-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0053_auto_20200516_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='YTCEbCvdD1uftZXPIr1Gu6JGYgYjkD3E', max_length=32),
        ),
    ]
