# Generated by Django 3.0.3 on 2020-05-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0054_auto_20200516_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentweight',
            name='assignment_type',
            field=models.CharField(choices=[('File Upload', 'File Upload'), ('Discussion', 'Discussion'), ('Quiz', 'Quiz'), ('Test', 'Test')], default='Pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='dAHiFdhu0eN3WloyUmDWiJWMxPf9hxi3', max_length=32),
        ),
    ]
