# Generated by Django 3.0.3 on 2020-05-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0055_auto_20200516_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment_type',
            field=models.CharField(choices=[('File Upload', 'File Upload'), ('Homework', 'Homework'), ('Discussion', 'Discussion'), ('Quiz', 'Quiz'), ('Test', 'Test')], default='Pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='assignmentweight',
            name='assignment_type',
            field=models.CharField(choices=[('File Upload', 'File Upload'), ('Homework', 'Homework'), ('Discussion', 'Discussion'), ('Quiz', 'Quiz'), ('Test', 'Test')], default='Pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='IhUqHUmmo8xf94YSnDCqAhK5TgyiPRFx', max_length=32),
        ),
    ]
