# Generated by Django 3.0.3 on 2020-05-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0056_auto_20200516_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='m2dAnnouncements',
            fields=[
                ('m2dannouncement_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_content', models.TextField(default='Announcement Coming Soon')),
                ('message_expiration_date', models.DateField()),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='sajjj5aIDiNYsj8P2ANJLYK9OpLzsWdz', max_length=32),
        ),
        migrations.CreateModel(
            name='classannouncements',
            fields=[
                ('class_announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_content', models.TextField(default='Pending')),
                ('message_expiration_date', models.DateField()),
                ('date_created', models.DateField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.ClassList')),
            ],
        ),
    ]
