# Generated by Django 3.0.3 on 2020-05-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0057_auto_20200516_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='bpcJZcZnr3qKz04a9wqhLMzXUrD1xZC7', max_length=32),
        ),
    ]
