# Generated by Django 3.0.3 on 2020-05-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0059_auto_20200516_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='classannouncements',
            name='pinned_message',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='bUJr6ZxaSssmCg4GUHpcw0aHjPhjorM1', max_length=32),
        ),
    ]
