# Generated by Django 3.0.3 on 2020-05-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0060_auto_20200516_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='j5f1S8JuRoIwn8msZWYbUmrAsbFqn6Ig', max_length=32),
        ),
    ]
