# Generated by Django 3.0.3 on 2020-05-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0061_auto_20200516_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='4iYRhGARAkdQT3L3JMNBtCmA43PPOuhG', max_length=32),
        ),
    ]
