# Generated by Django 3.0.3 on 2020-05-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0062_auto_20200516_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='Ykfim9etbdeOmqC8kWtnjKgBVneRESpH', max_length=32),
        ),
    ]
