# Generated by Django 3.0.3 on 2020-05-17 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LMSSystem', '0063_auto_20200516_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Fill In The Blank', 'Fill In The Blank'), ('Short Response', 'Short Response'), ('Essay', 'Essay'), ('Pending', 'Pending')], default='Pending', max_length=17)),
                ('question', models.TextField(default='Pending')),
                ('is_active', models.BooleanField(default=True)),
                ('assignment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.Assignments')),
            ],
        ),
        migrations.CreateModel(
            name='Question_choices',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_right_choice', models.BooleanField(default=False)),
                ('answer', models.TextField(default='Pending')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.Question')),
            ],
        ),
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='zNq5goMiBKJP4gNsxn8tZ4rlfbidngls', max_length=32),
        ),
        migrations.CreateModel(
            name='User_question_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DateTimeField()),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionchoice', to='LMSSystem.Question_choices')),
                ('is_right_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.Question_choices')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
