# Generated by Django 3.0.3 on 2020-05-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0064_auto_20200517_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='XGqLR611ISoFTrKO1XRlkZxndBeXMGg5', max_length=32),
        ),
    ]
