# Generated by Django 3.0.3 on 2020-05-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0066_auto_20200517_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlistgroupcode',
            name='class_group_code',
            field=models.CharField(default='b9u01roSmAvybSteV85jKZfKqhBsUvsl', max_length=32),
        ),
    ]
