# Generated by Django 3.0.3 on 2020-05-17 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LMSSystem', '0068_auto_20200517_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatMessages',
            fields=[
                ('group_msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_content', models.TextField(default='Pending')),
                ('pinned_message', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('msg_dts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='classannouncements',
            name='pinned_message',
        ),
        migrations.AddField(
            model_name='classannouncements',
            name='message_importance',
            field=models.CharField(choices=[('General', 'General'), ('Important', 'Important'), ('Critical', 'Critical')], default='General', max_length=9),
        ),
        migrations.AddField(
            model_name='m2dannouncements',
            name='message_attachments',
            field=models.FileField(blank=True, upload_to='system/'),
        ),
        migrations.AddField(
            model_name='m2dannouncements',
            name='message_importance',
            field=models.CharField(choices=[('General', 'General'), ('Important', 'Important'), ('Critical', 'Critical')], default='General', max_length=9),
        ),
        migrations.CreateModel(
            name='UserMessageGroupActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_read', models.BooleanField(default=False)),
                ('group_msg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.GroupChatMessages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessageChat',
            fields=[
                ('group_chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.Assignments')),
                ('class_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.ClassListGroup')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.ClassList')),
            ],
        ),
        migrations.AddField(
            model_name='groupchatmessages',
            name='group_chat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.GroupMessageChat'),
        ),
        migrations.AddField(
            model_name='groupchatmessages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupChatMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.GroupMessageChat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
