# Generated by Django 3.0.3 on 2020-05-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0070_classannouncements_pinned_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='classannouncements',
            name='message_type',
            field=models.CharField(choices=[('Assignment Posted', 'Assignment Posted'), ('General Announcement', 'General Announcement'), ('Class Cancelled', 'Class Cancelled')], default='General Announcement', max_length=30),
        ),
    ]
