# Generated by Django 3.0.3 on 2020-05-18 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LMSSystem', '0071_classannouncements_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment_type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('File Upload', 'File Upload'), ('Homework', 'Homework'), ('Discussion', 'Discussion'), ('Quiz', 'Quiz'), ('Test', 'Test')], default='Pending', max_length=11),
        ),
        migrations.CreateModel(
            name='StudentAssignments',
            fields=[
                ('student_assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_grade', models.IntegerField(blank=True, null=True)),
                ('assignment_status', models.CharField(choices=[('Not Submitted', 'Not Submitted'), ('Submitted - Not Graded', 'Submitted - Not Graded'), ('Graded', 'Graded'), ('Late', 'Late'), ('Resubmitted', 'Resubmitted')], default='Not Submitted', max_length=22)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.Assignments')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.ClassList')),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.ClassListGroupCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
