# Generated by Django 3.0.3 on 2020-05-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0072_auto_20200518_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentweight',
            name='assignment_type',
        ),
    ]
