# Generated by Django 3.0.3 on 2020-05-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0073_remove_assignmentweight_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentweight',
            name='assignment_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LMSSystem.Assignments'),
        ),
    ]
