# Generated by Django 3.0.3 on 2020-05-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSSystem', '0074_assignmentweight_assignment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentweight',
            name='assignment_type',
        ),
    ]
